version: "3.7"
services:
  api-gateway-scaffold:
    tty: true
    stdin_open: true
    build:
      context: .
      target: "development"
    image: "vcovre/api-gateway-scaffold"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
